name: Demo GitHub Actions Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build Script
        run: echo "Building the project... This is a placeholder for actual build steps."

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: build           

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Deploy Script
        run: echo "Deploying the project... This is a placeholder for actual deployment steps."