services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./Backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
